# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        object detection: 1
        semantic segmentation: 1
        image classification: 1
        computer vision: 1
        anomaly detection: 1
        state-of-the-art: 5
        noisy label: 3
        

# 通知の閾値
score_threshold: 3
